
services:
  db:
    image: mysql:8
    container_name: repli-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass       # cambia con la tua password
      MYSQL_DATABASE: repli_db            # nome del DB
      MYSQL_USER: repli_user              # utente DB
      MYSQL_PASSWORD: replipass           # password utente
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - repli-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: repli-backend
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ./backend:/app
    networks:
      - repli-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: repli-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    environment:
      - WEB_CONCURRENCY=1
    networks:
      - repli-network
    restart: unless-stopped

networks:
  repli-network:
    driver: bridge
